//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.04 at 07:25:36 PM CEST 
//


package org.orcid.jaxb.model.record_v3;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.orcid.jaxb.model.common_v3.AffiliationSummary;
import org.orcid.jaxb.model.common_v3.ExternalIds;
import org.orcid.jaxb.model.common_v3.LastModifiedDate;


/**
 * <p>Java class for affiliation-group complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="affiliation-group"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/common}last-modified-date" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/common}external-ids"/&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{http://www.orcid.org/ns/distinction}distinction-summary" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{http://www.orcid.org/ns/invited-position}invited-position-summary" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{http://www.orcid.org/ns/education}education-summary" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{http://www.orcid.org/ns/employment}employment-summary" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{http://www.orcid.org/ns/membership}membership-summary" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{http://www.orcid.org/ns/qualification}qualification-summary" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{http://www.orcid.org/ns/service}service-summary" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "affiliation-group", propOrder = {
    "lastModifiedDate",
    "externalIds",
    "distinctionSummary",
    "invitedPositionSummary",
    "educationSummary",
    "employmentSummary",
    "membershipSummary",
    "qualificationSummary",
    "serviceSummary"
})
@XmlSeeAlso({
    AffiliationGroup.class
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
public class AffiliationGroupType implements Serializable, ToString
{

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    private final static long serialVersionUID = 1L;
    @XmlElement(name = "last-modified-date", namespace = "http://www.orcid.org/ns/common")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    protected LastModifiedDate lastModifiedDate;
    @XmlElement(name = "external-ids", namespace = "http://www.orcid.org/ns/common", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    protected ExternalIds externalIds;
    @XmlElement(name = "distinction-summary", namespace = "http://www.orcid.org/ns/distinction")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    protected List<AffiliationSummary> distinctionSummary;
    @XmlElement(name = "invited-position-summary", namespace = "http://www.orcid.org/ns/invited-position")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    protected List<AffiliationSummary> invitedPositionSummary;
    @XmlElementRef(name = "education-summary", namespace = "http://www.orcid.org/ns/education", type = EducationSummary.class, required = false)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    protected List<EducationSummary> educationSummary;
    @XmlElementRef(name = "employment-summary", namespace = "http://www.orcid.org/ns/employment", type = EmploymentSummary.class, required = false)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    protected List<EmploymentSummary> employmentSummary;
    @XmlElement(name = "membership-summary", namespace = "http://www.orcid.org/ns/membership")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    protected List<AffiliationSummary> membershipSummary;
    @XmlElement(name = "qualification-summary", namespace = "http://www.orcid.org/ns/qualification")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    protected List<AffiliationSummary> qualificationSummary;
    @XmlElement(name = "service-summary", namespace = "http://www.orcid.org/ns/service")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    protected List<AffiliationSummary> serviceSummary;

    /**
     * Default no-arg constructor
     * 
     */
    public AffiliationGroupType() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public AffiliationGroupType(final LastModifiedDate lastModifiedDate, final ExternalIds externalIds, final List<AffiliationSummary> distinctionSummary, final List<AffiliationSummary> invitedPositionSummary, final List<EducationSummary> educationSummary, final List<EmploymentSummary> employmentSummary, final List<AffiliationSummary> membershipSummary, final List<AffiliationSummary> qualificationSummary, final List<AffiliationSummary> serviceSummary) {
        this.lastModifiedDate = lastModifiedDate;
        this.externalIds = externalIds;
        this.distinctionSummary = distinctionSummary;
        this.invitedPositionSummary = invitedPositionSummary;
        this.educationSummary = educationSummary;
        this.employmentSummary = employmentSummary;
        this.membershipSummary = membershipSummary;
        this.qualificationSummary = qualificationSummary;
        this.serviceSummary = serviceSummary;
    }

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link LastModifiedDate }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public LastModifiedDate getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link LastModifiedDate }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public void setLastModifiedDate(LastModifiedDate value) {
        this.lastModifiedDate = value;
    }

    /**
     * Gets the value of the externalIds property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalIds }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public ExternalIds getExternalIds() {
        return externalIds;
    }

    /**
     * Sets the value of the externalIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalIds }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public void setExternalIds(ExternalIds value) {
        this.externalIds = value;
    }

    /**
     * Gets the value of the distinctionSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the distinctionSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDistinctionSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AffiliationSummary }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public List<AffiliationSummary> getDistinctionSummary() {
        if (distinctionSummary == null) {
            distinctionSummary = new ArrayList<AffiliationSummary>();
        }
        return this.distinctionSummary;
    }

    /**
     * Gets the value of the invitedPositionSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invitedPositionSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvitedPositionSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AffiliationSummary }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public List<AffiliationSummary> getInvitedPositionSummary() {
        if (invitedPositionSummary == null) {
            invitedPositionSummary = new ArrayList<AffiliationSummary>();
        }
        return this.invitedPositionSummary;
    }

    /**
     * Gets the value of the educationSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the educationSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEducationSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EducationSummary }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public List<EducationSummary> getEducationSummary() {
        if (educationSummary == null) {
            educationSummary = new ArrayList<EducationSummary>();
        }
        return this.educationSummary;
    }

    /**
     * Gets the value of the employmentSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the employmentSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmploymentSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmploymentSummary }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public List<EmploymentSummary> getEmploymentSummary() {
        if (employmentSummary == null) {
            employmentSummary = new ArrayList<EmploymentSummary>();
        }
        return this.employmentSummary;
    }

    /**
     * Gets the value of the membershipSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the membershipSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMembershipSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AffiliationSummary }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public List<AffiliationSummary> getMembershipSummary() {
        if (membershipSummary == null) {
            membershipSummary = new ArrayList<AffiliationSummary>();
        }
        return this.membershipSummary;
    }

    /**
     * Gets the value of the qualificationSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualificationSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualificationSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AffiliationSummary }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public List<AffiliationSummary> getQualificationSummary() {
        if (qualificationSummary == null) {
            qualificationSummary = new ArrayList<AffiliationSummary>();
        }
        return this.qualificationSummary;
    }

    /**
     * Gets the value of the serviceSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AffiliationSummary }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public List<AffiliationSummary> getServiceSummary() {
        if (serviceSummary == null) {
            serviceSummary = new ArrayList<AffiliationSummary>();
        }
        return this.serviceSummary;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public void setDistinctionSummary(List<AffiliationSummary> value) {
        this.distinctionSummary = null;
        if (value!= null) {
            List<AffiliationSummary> draftl = this.getDistinctionSummary();
            draftl.addAll(value);
        }
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public void setInvitedPositionSummary(List<AffiliationSummary> value) {
        this.invitedPositionSummary = null;
        if (value!= null) {
            List<AffiliationSummary> draftl = this.getInvitedPositionSummary();
            draftl.addAll(value);
        }
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public void setEducationSummary(List<EducationSummary> value) {
        this.educationSummary = null;
        if (value!= null) {
            List<EducationSummary> draftl = this.getEducationSummary();
            draftl.addAll(value);
        }
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public void setEmploymentSummary(List<EmploymentSummary> value) {
        this.employmentSummary = null;
        if (value!= null) {
            List<EmploymentSummary> draftl = this.getEmploymentSummary();
            draftl.addAll(value);
        }
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public void setMembershipSummary(List<AffiliationSummary> value) {
        this.membershipSummary = null;
        if (value!= null) {
            List<AffiliationSummary> draftl = this.getMembershipSummary();
            draftl.addAll(value);
        }
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public void setQualificationSummary(List<AffiliationSummary> value) {
        this.qualificationSummary = null;
        if (value!= null) {
            List<AffiliationSummary> draftl = this.getQualificationSummary();
            draftl.addAll(value);
        }
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public void setServiceSummary(List<AffiliationSummary> value) {
        this.serviceSummary = null;
        if (value!= null) {
            List<AffiliationSummary> draftl = this.getServiceSummary();
            draftl.addAll(value);
        }
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-04T07:25:36+02:00", comments = "JAXB RI v2.2.11")
    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            LastModifiedDate theLastModifiedDate;
            theLastModifiedDate = this.getLastModifiedDate();
            strategy.appendField(locator, this, "lastModifiedDate", buffer, theLastModifiedDate);
        }
        {
            ExternalIds theExternalIds;
            theExternalIds = this.getExternalIds();
            strategy.appendField(locator, this, "externalIds", buffer, theExternalIds);
        }
        {
            List<AffiliationSummary> theDistinctionSummary;
            theDistinctionSummary = (((this.distinctionSummary!= null)&&(!this.distinctionSummary.isEmpty()))?this.getDistinctionSummary():null);
            strategy.appendField(locator, this, "distinctionSummary", buffer, theDistinctionSummary);
        }
        {
            List<AffiliationSummary> theInvitedPositionSummary;
            theInvitedPositionSummary = (((this.invitedPositionSummary!= null)&&(!this.invitedPositionSummary.isEmpty()))?this.getInvitedPositionSummary():null);
            strategy.appendField(locator, this, "invitedPositionSummary", buffer, theInvitedPositionSummary);
        }
        {
            List<EducationSummary> theEducationSummary;
            theEducationSummary = (((this.educationSummary!= null)&&(!this.educationSummary.isEmpty()))?this.getEducationSummary():null);
            strategy.appendField(locator, this, "educationSummary", buffer, theEducationSummary);
        }
        {
            List<EmploymentSummary> theEmploymentSummary;
            theEmploymentSummary = (((this.employmentSummary!= null)&&(!this.employmentSummary.isEmpty()))?this.getEmploymentSummary():null);
            strategy.appendField(locator, this, "employmentSummary", buffer, theEmploymentSummary);
        }
        {
            List<AffiliationSummary> theMembershipSummary;
            theMembershipSummary = (((this.membershipSummary!= null)&&(!this.membershipSummary.isEmpty()))?this.getMembershipSummary():null);
            strategy.appendField(locator, this, "membershipSummary", buffer, theMembershipSummary);
        }
        {
            List<AffiliationSummary> theQualificationSummary;
            theQualificationSummary = (((this.qualificationSummary!= null)&&(!this.qualificationSummary.isEmpty()))?this.getQualificationSummary():null);
            strategy.appendField(locator, this, "qualificationSummary", buffer, theQualificationSummary);
        }
        {
            List<AffiliationSummary> theServiceSummary;
            theServiceSummary = (((this.serviceSummary!= null)&&(!this.serviceSummary.isEmpty()))?this.getServiceSummary():null);
            strategy.appendField(locator, this, "serviceSummary", buffer, theServiceSummary);
        }
        return buffer;
    }

}
