//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 07:22:19 PM CEST 
//


package org.orcid.jaxb.model.record_v3;

import java.io.Serializable;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.orcid.jaxb.model.common_v3.LastModifiedDate;
import org.orcid.jaxb.model.common_v3.SourceType;
import org.orcid.jaxb.model.common_v3.Visibility;


/**
 * The history of the researcher's ORCID record
 * 				
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="creation-method" type="{http://www.orcid.org/ns/history}creation-method" minOccurs="0"/&gt;
 *         &lt;element name="completion-date" type="{http://www.orcid.org/ns/history}completion-date" minOccurs="0"/&gt;
 *         &lt;element name="submission-date" type="{http://www.orcid.org/ns/history}submission-date" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/common}last-modified-date" minOccurs="0"/&gt;
 *         &lt;element name="claimed" type="{http://www.orcid.org/ns/history}claimed" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/common}source" minOccurs="0"/&gt;
 *         &lt;element name="deactivation-date" type="{http://www.orcid.org/ns/history}deactivation-date" minOccurs="0"/&gt;
 *         &lt;element name="verified-email" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="verified-primary-email" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="visibility" type="{http://www.orcid.org/ns/common}visibility" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "creationMethod",
    "completionDate",
    "submissionDate",
    "lastModifiedDate",
    "claimed",
    "source",
    "deactivationDate",
    "verifiedEmail",
    "verifiedPrimaryEmail"
})
@XmlRootElement(name = "history", namespace = "http://www.orcid.org/ns/history")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
public class History implements Serializable, ToString
{

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    private final static long serialVersionUID = 1L;
    @XmlElement(name = "creation-method", namespace = "http://www.orcid.org/ns/history")
    @XmlSchemaType(name = "string")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected CreationMethod creationMethod;
    @XmlElement(name = "completion-date", namespace = "http://www.orcid.org/ns/history")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected CompletionDate completionDate;
    @XmlElement(name = "submission-date", namespace = "http://www.orcid.org/ns/history")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected SubmissionDate submissionDate;
    @XmlElement(name = "last-modified-date", namespace = "http://www.orcid.org/ns/common")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected LastModifiedDate lastModifiedDate;
    @XmlElement(namespace = "http://www.orcid.org/ns/history")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected Claimed claimed;
    @XmlElement(namespace = "http://www.orcid.org/ns/common")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected SourceType source;
    @XmlElement(name = "deactivation-date", namespace = "http://www.orcid.org/ns/history")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected DeactivationDate deactivationDate;
    @XmlElement(name = "verified-email", namespace = "http://www.orcid.org/ns/history")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected boolean verifiedEmail;
    @XmlElement(name = "verified-primary-email", namespace = "http://www.orcid.org/ns/history")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected boolean verifiedPrimaryEmail;
    @XmlAttribute(name = "visibility")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected Visibility visibility;

    /**
     * Default no-arg constructor
     * 
     */
    public History() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public History(final CreationMethod creationMethod, final CompletionDate completionDate, final SubmissionDate submissionDate, final LastModifiedDate lastModifiedDate, final Claimed claimed, final SourceType source, final DeactivationDate deactivationDate, final boolean verifiedEmail, final boolean verifiedPrimaryEmail, final Visibility visibility) {
        this.creationMethod = creationMethod;
        this.completionDate = completionDate;
        this.submissionDate = submissionDate;
        this.lastModifiedDate = lastModifiedDate;
        this.claimed = claimed;
        this.source = source;
        this.deactivationDate = deactivationDate;
        this.verifiedEmail = verifiedEmail;
        this.verifiedPrimaryEmail = verifiedPrimaryEmail;
        this.visibility = visibility;
    }

    /**
     * Gets the value of the creationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link CreationMethod }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public CreationMethod getCreationMethod() {
        return creationMethod;
    }

    /**
     * Sets the value of the creationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreationMethod }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setCreationMethod(CreationMethod value) {
        this.creationMethod = value;
    }

    /**
     * Gets the value of the completionDate property.
     * 
     * @return
     *     possible object is
     *     {@link CompletionDate }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public CompletionDate getCompletionDate() {
        return completionDate;
    }

    /**
     * Sets the value of the completionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompletionDate }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setCompletionDate(CompletionDate value) {
        this.completionDate = value;
    }

    /**
     * Gets the value of the submissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link SubmissionDate }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public SubmissionDate getSubmissionDate() {
        return submissionDate;
    }

    /**
     * Sets the value of the submissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmissionDate }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setSubmissionDate(SubmissionDate value) {
        this.submissionDate = value;
    }

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link LastModifiedDate }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public LastModifiedDate getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link LastModifiedDate }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setLastModifiedDate(LastModifiedDate value) {
        this.lastModifiedDate = value;
    }

    /**
     * Gets the value of the claimed property.
     * 
     * @return
     *     possible object is
     *     {@link Claimed }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public Claimed getClaimed() {
        return claimed;
    }

    /**
     * Sets the value of the claimed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Claimed }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setClaimed(Claimed value) {
        this.claimed = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link SourceType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public SourceType getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setSource(SourceType value) {
        this.source = value;
    }

    /**
     * Gets the value of the deactivationDate property.
     * 
     * @return
     *     possible object is
     *     {@link DeactivationDate }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public DeactivationDate getDeactivationDate() {
        return deactivationDate;
    }

    /**
     * Sets the value of the deactivationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeactivationDate }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setDeactivationDate(DeactivationDate value) {
        this.deactivationDate = value;
    }

    /**
     * Gets the value of the verifiedEmail property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public boolean isVerifiedEmail() {
        return verifiedEmail;
    }

    /**
     * Sets the value of the verifiedEmail property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setVerifiedEmail(boolean value) {
        this.verifiedEmail = value;
    }

    /**
     * Gets the value of the verifiedPrimaryEmail property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public boolean isVerifiedPrimaryEmail() {
        return verifiedPrimaryEmail;
    }

    /**
     * Sets the value of the verifiedPrimaryEmail property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setVerifiedPrimaryEmail(boolean value) {
        this.verifiedPrimaryEmail = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link Visibility }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public Visibility getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Visibility }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setVisibility(Visibility value) {
        this.visibility = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            CreationMethod theCreationMethod;
            theCreationMethod = this.getCreationMethod();
            strategy.appendField(locator, this, "creationMethod", buffer, theCreationMethod);
        }
        {
            CompletionDate theCompletionDate;
            theCompletionDate = this.getCompletionDate();
            strategy.appendField(locator, this, "completionDate", buffer, theCompletionDate);
        }
        {
            SubmissionDate theSubmissionDate;
            theSubmissionDate = this.getSubmissionDate();
            strategy.appendField(locator, this, "submissionDate", buffer, theSubmissionDate);
        }
        {
            LastModifiedDate theLastModifiedDate;
            theLastModifiedDate = this.getLastModifiedDate();
            strategy.appendField(locator, this, "lastModifiedDate", buffer, theLastModifiedDate);
        }
        {
            Claimed theClaimed;
            theClaimed = this.getClaimed();
            strategy.appendField(locator, this, "claimed", buffer, theClaimed);
        }
        {
            SourceType theSource;
            theSource = this.getSource();
            strategy.appendField(locator, this, "source", buffer, theSource);
        }
        {
            DeactivationDate theDeactivationDate;
            theDeactivationDate = this.getDeactivationDate();
            strategy.appendField(locator, this, "deactivationDate", buffer, theDeactivationDate);
        }
        {
            boolean theVerifiedEmail;
            theVerifiedEmail = this.isVerifiedEmail();
            strategy.appendField(locator, this, "verifiedEmail", buffer, theVerifiedEmail);
        }
        {
            boolean theVerifiedPrimaryEmail;
            theVerifiedPrimaryEmail = this.isVerifiedPrimaryEmail();
            strategy.appendField(locator, this, "verifiedPrimaryEmail", buffer, theVerifiedPrimaryEmail);
        }
        {
            Visibility theVisibility;
            theVisibility = this.getVisibility();
            strategy.appendField(locator, this, "visibility", buffer, theVisibility);
        }
        return buffer;
    }

}
