//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 09:44:26 AM CEST 
//


package org.orcid.jaxb.model.record_v3;

import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import org.orcid.jaxb.model.common_v3.Affiliation;
import org.orcid.jaxb.model.common_v3.AffiliationSummary;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.orcid.jaxb.model.record_v3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.orcid.jaxb.model.record_v3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link WorkBulk }
     * 
     */
    public WorkBulk createWorkBulk() {
        return new WorkBulk();
    }

    /**
     * Create an instance of {@link Work }
     * 
     */
    public Work createWork() {
        return new Work();
    }

    /**
     * Create an instance of {@link WorkTitle }
     * 
     */
    public WorkTitle createWorkTitle() {
        return new WorkTitle();
    }

    /**
     * Create an instance of {@link Citation }
     * 
     */
    public Citation createCitation() {
        return new Citation();
    }

    /**
     * Create an instance of {@link WorkContributors }
     * 
     */
    public WorkContributors createWorkContributors() {
        return new WorkContributors();
    }

    /**
     * Create an instance of {@link WorkSummary }
     * 
     */
    public WorkSummary createWorkSummary() {
        return new WorkSummary();
    }

    /**
     * Create an instance of {@link Contributor }
     * 
     */
    public Contributor createContributor() {
        return new Contributor();
    }

    /**
     * Create an instance of {@link ContributorEmail }
     * 
     */
    public ContributorEmail createContributorEmail() {
        return new ContributorEmail();
    }

    /**
     * Create an instance of {@link ContributorAttributes }
     * 
     */
    public ContributorAttributes createContributorAttributes() {
        return new ContributorAttributes();
    }

    /**
     * Create an instance of {@link ExternalIdentifiers }
     * 
     */
    public ExternalIdentifiers createExternalIdentifiers() {
        return new ExternalIdentifiers();
    }

    /**
     * Create an instance of {@link ExternalIdentifier }
     * 
     */
    public ExternalIdentifier createExternalIdentifier() {
        return new ExternalIdentifier();
    }

    /**
     * Create an instance of {@link PeerReview }
     * 
     */
    public PeerReview createPeerReview() {
        return new PeerReview();
    }

    /**
     * Create an instance of {@link SubjectName }
     * 
     */
    public SubjectName createSubjectName() {
        return new SubjectName();
    }

    /**
     * Create an instance of {@link PeerReviewSummary }
     * 
     */
    public PeerReviewSummary createPeerReviewSummary() {
        return new PeerReviewSummary();
    }

    /**
     * Create an instance of {@link ResearchResource }
     * 
     */
    public ResearchResource createResearchResource() {
        return new ResearchResource();
    }

    /**
     * Create an instance of {@link ResearchResourceProposal }
     * 
     */
    public ResearchResourceProposal createResearchResourceProposal() {
        return new ResearchResourceProposal();
    }

    /**
     * Create an instance of {@link ResearchResourceItems }
     * 
     */
    public ResearchResourceItems createResearchResourceItems() {
        return new ResearchResourceItems();
    }

    /**
     * Create an instance of {@link ResearchResourceSummary }
     * 
     */
    public ResearchResourceSummary createResearchResourceSummary() {
        return new ResearchResourceSummary();
    }

    /**
     * Create an instance of {@link ResearchResourceItem }
     * 
     */
    public ResearchResourceItem createResearchResourceItem() {
        return new ResearchResourceItem();
    }

    /**
     * Create an instance of {@link ResearchResourceHosts }
     * 
     */
    public ResearchResourceHosts createResearchResourceHosts() {
        return new ResearchResourceHosts();
    }

    /**
     * Create an instance of {@link ResearchResourceTitle }
     * 
     */
    public ResearchResourceTitle createResearchResourceTitle() {
        return new ResearchResourceTitle();
    }

    /**
     * Create an instance of {@link Preferences }
     * 
     */
    public Preferences createPreferences() {
        return new Preferences();
    }

    /**
     * Create an instance of {@link Funding }
     * 
     */
    public Funding createFunding() {
        return new Funding();
    }

    /**
     * Create an instance of {@link FundingTitle }
     * 
     */
    public FundingTitle createFundingTitle() {
        return new FundingTitle();
    }

    /**
     * Create an instance of {@link FundingContributors }
     * 
     */
    public FundingContributors createFundingContributors() {
        return new FundingContributors();
    }

    /**
     * Create an instance of {@link FundingSummary }
     * 
     */
    public FundingSummary createFundingSummary() {
        return new FundingSummary();
    }

    /**
     * Create an instance of {@link FundingContributor }
     * 
     */
    public FundingContributor createFundingContributor() {
        return new FundingContributor();
    }

    /**
     * Create an instance of {@link FundingContributorAttributes }
     * 
     */
    public FundingContributorAttributes createFundingContributorAttributes() {
        return new FundingContributorAttributes();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link OtherNames }
     * 
     */
    public OtherNames createOtherNames() {
        return new OtherNames();
    }

    /**
     * Create an instance of {@link OtherNameType }
     * 
     */
    public OtherNameType createOtherNameType() {
        return new OtherNameType();
    }

    /**
     * Create an instance of {@link BiographyType }
     * 
     */
    public BiographyType createBiographyType() {
        return new BiographyType();
    }

    /**
     * Create an instance of {@link ResearcherUrls }
     * 
     */
    public ResearcherUrls createResearcherUrls() {
        return new ResearcherUrls();
    }

    /**
     * Create an instance of {@link ResearcherUrlType }
     * 
     */
    public ResearcherUrlType createResearcherUrlType() {
        return new ResearcherUrlType();
    }

    /**
     * Create an instance of {@link Emails }
     * 
     */
    public Emails createEmails() {
        return new Emails();
    }

    /**
     * Create an instance of {@link EmailType }
     * 
     */
    public EmailType createEmailType() {
        return new EmailType();
    }

    /**
     * Create an instance of {@link Addresses }
     * 
     */
    public Addresses createAddresses() {
        return new Addresses();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link Keywords }
     * 
     */
    public Keywords createKeywords() {
        return new Keywords();
    }

    /**
     * Create an instance of {@link KeywordType }
     * 
     */
    public KeywordType createKeywordType() {
        return new KeywordType();
    }

    /**
     * Create an instance of {@link PersonalDetails }
     * 
     */
    public PersonalDetails createPersonalDetails() {
        return new PersonalDetails();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link NameType.GivenNames }
     * 
     */
    public NameType.GivenNames createNameTypeGivenNames() {
        return new NameType.GivenNames();
    }

    /**
     * Create an instance of {@link NameType.FamilyName }
     * 
     */
    public NameType.FamilyName createNameTypeFamilyName() {
        return new NameType.FamilyName();
    }

    /**
     * Create an instance of {@link NameType.CreditName }
     * 
     */
    public NameType.CreditName createNameTypeCreditName() {
        return new NameType.CreditName();
    }

    /**
     * Create an instance of {@link org.orcid.jaxb.model.record_v3.CreditName }
     * 
     */
    public org.orcid.jaxb.model.record_v3.CreditName createCreditName() {
        return new org.orcid.jaxb.model.record_v3.CreditName();
    }

    /**
     * Create an instance of {@link CreditNameType }
     * 
     */
    public CreditNameType createCreditNameType() {
        return new CreditNameType();
    }

    /**
     * Create an instance of {@link Biography }
     * 
     */
    public Biography createBiography() {
        return new Biography();
    }

    /**
     * Create an instance of {@link OtherName }
     * 
     */
    public OtherName createOtherName() {
        return new OtherName();
    }

    /**
     * Create an instance of {@link ResearcherUrl }
     * 
     */
    public ResearcherUrl createResearcherUrl() {
        return new ResearcherUrl();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link ActivitiesSummary }
     * 
     */
    public ActivitiesSummary createActivitiesSummary() {
        return new ActivitiesSummary();
    }

    /**
     * Create an instance of {@link DistinctionsType }
     * 
     */
    public DistinctionsType createDistinctionsType() {
        return new DistinctionsType();
    }

    /**
     * Create an instance of {@link EducationsType }
     * 
     */
    public EducationsType createEducationsType() {
        return new EducationsType();
    }

    /**
     * Create an instance of {@link EmploymentsType }
     * 
     */
    public EmploymentsType createEmploymentsType() {
        return new EmploymentsType();
    }

    /**
     * Create an instance of {@link FundingsType }
     * 
     */
    public FundingsType createFundingsType() {
        return new FundingsType();
    }

    /**
     * Create an instance of {@link InvitedPositionsType }
     * 
     */
    public InvitedPositionsType createInvitedPositionsType() {
        return new InvitedPositionsType();
    }

    /**
     * Create an instance of {@link MembershipsType }
     * 
     */
    public MembershipsType createMembershipsType() {
        return new MembershipsType();
    }

    /**
     * Create an instance of {@link PeerReviewsType }
     * 
     */
    public PeerReviewsType createPeerReviewsType() {
        return new PeerReviewsType();
    }

    /**
     * Create an instance of {@link QualificationsType }
     * 
     */
    public QualificationsType createQualificationsType() {
        return new QualificationsType();
    }

    /**
     * Create an instance of {@link ResearchResourcesType }
     * 
     */
    public ResearchResourcesType createResearchResourcesType() {
        return new ResearchResourcesType();
    }

    /**
     * Create an instance of {@link ServicesType }
     * 
     */
    public ServicesType createServicesType() {
        return new ServicesType();
    }

    /**
     * Create an instance of {@link WorksType }
     * 
     */
    public WorksType createWorksType() {
        return new WorksType();
    }

    /**
     * Create an instance of {@link ResearchResources }
     * 
     */
    public ResearchResources createResearchResources() {
        return new ResearchResources();
    }

    /**
     * Create an instance of {@link ResearchResourceGroup }
     * 
     */
    public ResearchResourceGroup createResearchResourceGroup() {
        return new ResearchResourceGroup();
    }

    /**
     * Create an instance of {@link Distinctions }
     * 
     */
    public Distinctions createDistinctions() {
        return new Distinctions();
    }

    /**
     * Create an instance of {@link AffiliationGroup }
     * 
     */
    public AffiliationGroup createAffiliationGroup() {
        return new AffiliationGroup();
    }

    /**
     * Create an instance of {@link AffiliationGroupType }
     * 
     */
    public AffiliationGroupType createAffiliationGroupType() {
        return new AffiliationGroupType();
    }

    /**
     * Create an instance of {@link Educations }
     * 
     */
    public Educations createEducations() {
        return new Educations();
    }

    /**
     * Create an instance of {@link Employments }
     * 
     */
    public Employments createEmployments() {
        return new Employments();
    }

    /**
     * Create an instance of {@link InvitedPositions }
     * 
     */
    public InvitedPositions createInvitedPositions() {
        return new InvitedPositions();
    }

    /**
     * Create an instance of {@link Fundings }
     * 
     */
    public Fundings createFundings() {
        return new Fundings();
    }

    /**
     * Create an instance of {@link FundingGroup }
     * 
     */
    public FundingGroup createFundingGroup() {
        return new FundingGroup();
    }

    /**
     * Create an instance of {@link Memberships }
     * 
     */
    public Memberships createMemberships() {
        return new Memberships();
    }

    /**
     * Create an instance of {@link PeerReviews }
     * 
     */
    public PeerReviews createPeerReviews() {
        return new PeerReviews();
    }

    /**
     * Create an instance of {@link PeerReviewGroup }
     * 
     */
    public PeerReviewGroup createPeerReviewGroup() {
        return new PeerReviewGroup();
    }

    /**
     * Create an instance of {@link Qualifications }
     * 
     */
    public Qualifications createQualifications() {
        return new Qualifications();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link Works }
     * 
     */
    public Works createWorks() {
        return new Works();
    }

    /**
     * Create an instance of {@link WorkGroup }
     * 
     */
    public WorkGroup createWorkGroup() {
        return new WorkGroup();
    }

    /**
     * Create an instance of {@link PeerReviewDuplicates }
     * 
     */
    public PeerReviewDuplicates createPeerReviewDuplicates() {
        return new PeerReviewDuplicates();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link CompletionDate }
     * 
     */
    public CompletionDate createCompletionDate() {
        return new CompletionDate();
    }

    /**
     * Create an instance of {@link SubmissionDate }
     * 
     */
    public SubmissionDate createSubmissionDate() {
        return new SubmissionDate();
    }

    /**
     * Create an instance of {@link Claimed }
     * 
     */
    public Claimed createClaimed() {
        return new Claimed();
    }

    /**
     * Create an instance of {@link DeactivationDate }
     * 
     */
    public DeactivationDate createDeactivationDate() {
        return new DeactivationDate();
    }

    /**
     * Create an instance of {@link SourceReference }
     * 
     */
    public SourceReference createSourceReference() {
        return new SourceReference();
    }

    /**
     * Create an instance of {@link SourceDate }
     * 
     */
    public SourceDate createSourceDate() {
        return new SourceDate();
    }

    /**
     * Create an instance of {@link Service }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/service", name = "service")
    public Service createService(Affiliation value) {
        return new Service(value);
    }

    /**
     * Create an instance of {@link ServiceSummary }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/service", name = "service-summary")
    public ServiceSummary createServiceSummary(AffiliationSummary value) {
        return new ServiceSummary(value);
    }

    /**
     * Create an instance of {@link InvitedPosition }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/invited-position", name = "invited-position")
    public InvitedPosition createInvitedPosition(Affiliation value) {
        return new InvitedPosition(value);
    }

    /**
     * Create an instance of {@link InvitedPositionSummary }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/invited-position", name = "invited-position-summary")
    public InvitedPositionSummary createInvitedPositionSummary(AffiliationSummary value) {
        return new InvitedPositionSummary(value);
    }

    /**
     * Create an instance of {@link Employment }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/employment", name = "employment")
    public Employment createEmployment(Affiliation value) {
        return new Employment(value);
    }

    /**
     * Create an instance of {@link EmploymentSummary }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/employment", name = "employment-summary")
    public EmploymentSummary createEmploymentSummary(AffiliationSummary value) {
        return new EmploymentSummary(value);
    }

    /**
     * Create an instance of {@link Membership }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/membership", name = "membership")
    public Membership createMembership(Affiliation value) {
        return new Membership(value);
    }

    /**
     * Create an instance of {@link MembershipSummary }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/membership", name = "membership-summary")
    public MembershipSummary createMembershipSummary(AffiliationSummary value) {
        return new MembershipSummary(value);
    }

    /**
     * Create an instance of {@link Education }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/education", name = "education")
    public Education createEducation(Affiliation value) {
        return new Education(value);
    }

    /**
     * Create an instance of {@link EducationSummary }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/education", name = "education-summary")
    public EducationSummary createEducationSummary(AffiliationSummary value) {
        return new EducationSummary(value);
    }

    /**
     * Create an instance of {@link DistinctionSummary }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/distinction", name = "distinction-summary")
    public DistinctionSummary createDistinctionSummary(AffiliationSummary value) {
        return new DistinctionSummary(value);
    }

    /**
     * Create an instance of {@link QualificationSummary }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/qualification", name = "qualification-summary")
    public QualificationSummary createQualificationSummary(AffiliationSummary value) {
        return new QualificationSummary(value);
    }

    /**
     * Create an instance of {@link Distinction }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/distinction", name = "distinction")
    public Distinction createDistinction(Affiliation value) {
        return new Distinction(value);
    }

    /**
     * Create an instance of {@link Qualification }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/qualification", name = "qualification")
    public Qualification createQualification(Affiliation value) {
        return new Qualification(value);
    }

}
