//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.24 at 11:17:38 AM CDT 
//


package org.orcid.jaxb.model.common_v2;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for client-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="client-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="creator"/&gt;
 *     &lt;enumeration value="premium-creator"/&gt;
 *     &lt;enumeration value="updater"/&gt;
 *     &lt;enumeration value="premium-updater"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "client-type")
@XmlEnum
@Generated(value = "com.sun.tools.xjc.Driver", date = "2018-04-24T11:17:38-05:00", comments = "JAXB RI v2.2.11")
public enum ClientType {

    @XmlEnumValue("creator")
    CREATOR("creator"),
    @XmlEnumValue("premium-creator")
    PREMIUM_CREATOR("premium-creator"),
    @XmlEnumValue("updater")
    UPDATER("updater"),
    @XmlEnumValue("premium-updater")
    PREMIUM_UPDATER("premium-updater");
    private final String value;

    ClientType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ClientType fromValue(String v) {
        for (ClientType c: ClientType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
