//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.24 at 11:17:38 AM CDT 
//


package org.orcid.jaxb.model.common_v2;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contributor-role.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="contributor-role"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="author"/&gt;
 *     &lt;enumeration value="assignee"/&gt;
 *     &lt;enumeration value="editor"/&gt;
 *     &lt;enumeration value="chair-or-translator"/&gt;
 *     &lt;enumeration value="co-investigator"/&gt;
 *     &lt;enumeration value="co-inventor"/&gt;
 *     &lt;enumeration value="graduate-student"/&gt;
 *     &lt;enumeration value="other-inventor"/&gt;
 *     &lt;enumeration value="principal-investigator"/&gt;
 *     &lt;enumeration value="postdoctoral-researcher"/&gt;
 *     &lt;enumeration value="support-staff"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "contributor-role")
@XmlEnum
@Generated(value = "com.sun.tools.xjc.Driver", date = "2018-04-24T11:17:38-05:00", comments = "JAXB RI v2.2.11")
public enum ContributorRole {

    @XmlEnumValue("author")
    AUTHOR("author"),
    @XmlEnumValue("assignee")
    ASSIGNEE("assignee"),
    @XmlEnumValue("editor")
    EDITOR("editor"),
    @XmlEnumValue("chair-or-translator")
    CHAIR_OR_TRANSLATOR("chair-or-translator"),
    @XmlEnumValue("co-investigator")
    CO_INVESTIGATOR("co-investigator"),
    @XmlEnumValue("co-inventor")
    CO_INVENTOR("co-inventor"),
    @XmlEnumValue("graduate-student")
    GRADUATE_STUDENT("graduate-student"),
    @XmlEnumValue("other-inventor")
    OTHER_INVENTOR("other-inventor"),
    @XmlEnumValue("principal-investigator")
    PRINCIPAL_INVESTIGATOR("principal-investigator"),
    @XmlEnumValue("postdoctoral-researcher")
    POSTDOCTORAL_RESEARCHER("postdoctoral-researcher"),
    @XmlEnumValue("support-staff")
    SUPPORT_STAFF("support-staff");
    private final String value;

    ContributorRole(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContributorRole fromValue(String v) {
        for (ContributorRole c: ContributorRole.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
