//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.24 at 11:17:38 AM CDT 
//


package org.orcid.jaxb.model.common_v2;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for language-code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="language-code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="en"/&gt;
 *     &lt;enumeration value="ab"/&gt;
 *     &lt;enumeration value="aa"/&gt;
 *     &lt;enumeration value="af"/&gt;
 *     &lt;enumeration value="ak"/&gt;
 *     &lt;enumeration value="sq"/&gt;
 *     &lt;enumeration value="am"/&gt;
 *     &lt;enumeration value="ar"/&gt;
 *     &lt;enumeration value="an"/&gt;
 *     &lt;enumeration value="hy"/&gt;
 *     &lt;enumeration value="as"/&gt;
 *     &lt;enumeration value="av"/&gt;
 *     &lt;enumeration value="ae"/&gt;
 *     &lt;enumeration value="ay"/&gt;
 *     &lt;enumeration value="az"/&gt;
 *     &lt;enumeration value="bm"/&gt;
 *     &lt;enumeration value="ba"/&gt;
 *     &lt;enumeration value="eu"/&gt;
 *     &lt;enumeration value="be"/&gt;
 *     &lt;enumeration value="bn"/&gt;
 *     &lt;enumeration value="bh"/&gt;
 *     &lt;enumeration value="bi"/&gt;
 *     &lt;enumeration value="bs"/&gt;
 *     &lt;enumeration value="br"/&gt;
 *     &lt;enumeration value="bg"/&gt;
 *     &lt;enumeration value="my"/&gt;
 *     &lt;enumeration value="ca"/&gt;
 *     &lt;enumeration value="ch"/&gt;
 *     &lt;enumeration value="ce"/&gt;
 *     &lt;enumeration value="zh_CN"/&gt;
 *     &lt;enumeration value="zh_TW"/&gt;
 *     &lt;enumeration value="cu"/&gt;
 *     &lt;enumeration value="cv"/&gt;
 *     &lt;enumeration value="kw"/&gt;
 *     &lt;enumeration value="co"/&gt;
 *     &lt;enumeration value="cr"/&gt;
 *     &lt;enumeration value="hr"/&gt;
 *     &lt;enumeration value="cs"/&gt;
 *     &lt;enumeration value="da"/&gt;
 *     &lt;enumeration value="dv"/&gt;
 *     &lt;enumeration value="nl"/&gt;
 *     &lt;enumeration value="dz"/&gt;
 *     &lt;enumeration value="en"/&gt;
 *     &lt;enumeration value="eo"/&gt;
 *     &lt;enumeration value="et"/&gt;
 *     &lt;enumeration value="ee"/&gt;
 *     &lt;enumeration value="fo"/&gt;
 *     &lt;enumeration value="fj"/&gt;
 *     &lt;enumeration value="fi"/&gt;
 *     &lt;enumeration value="fr"/&gt;
 *     &lt;enumeration value="fy"/&gt;
 *     &lt;enumeration value="ff"/&gt;
 *     &lt;enumeration value="gl"/&gt;
 *     &lt;enumeration value="lg"/&gt;
 *     &lt;enumeration value="ka"/&gt;
 *     &lt;enumeration value="de"/&gt;
 *     &lt;enumeration value="el"/&gt;
 *     &lt;enumeration value="kl"/&gt;
 *     &lt;enumeration value="gn"/&gt;
 *     &lt;enumeration value="gu"/&gt;
 *     &lt;enumeration value="ht"/&gt;
 *     &lt;enumeration value="ha"/&gt;
 *     &lt;enumeration value="iw"/&gt;
 *     &lt;enumeration value="hz"/&gt;
 *     &lt;enumeration value="hi"/&gt;
 *     &lt;enumeration value="ho"/&gt;
 *     &lt;enumeration value="hu"/&gt;
 *     &lt;enumeration value="is"/&gt;
 *     &lt;enumeration value="io"/&gt;
 *     &lt;enumeration value="ig"/&gt;
 *     &lt;enumeration value="in"/&gt;
 *     &lt;enumeration value="ia"/&gt;
 *     &lt;enumeration value="ie"/&gt;
 *     &lt;enumeration value="iu"/&gt;
 *     &lt;enumeration value="ik"/&gt;
 *     &lt;enumeration value="ga"/&gt;
 *     &lt;enumeration value="it"/&gt;
 *     &lt;enumeration value="ja"/&gt;
 *     &lt;enumeration value="jv"/&gt;
 *     &lt;enumeration value="kn"/&gt;
 *     &lt;enumeration value="kr"/&gt;
 *     &lt;enumeration value="ks"/&gt;
 *     &lt;enumeration value="kk"/&gt;
 *     &lt;enumeration value="km"/&gt;
 *     &lt;enumeration value="ki"/&gt;
 *     &lt;enumeration value="rw"/&gt;
 *     &lt;enumeration value="ky"/&gt;
 *     &lt;enumeration value="kv"/&gt;
 *     &lt;enumeration value="kg"/&gt;
 *     &lt;enumeration value="ko"/&gt;
 *     &lt;enumeration value="ku"/&gt;
 *     &lt;enumeration value="kj"/&gt;
 *     &lt;enumeration value="lo"/&gt;
 *     &lt;enumeration value="la"/&gt;
 *     &lt;enumeration value="lv"/&gt;
 *     &lt;enumeration value="li"/&gt;
 *     &lt;enumeration value="ln"/&gt;
 *     &lt;enumeration value="lt"/&gt;
 *     &lt;enumeration value="lu"/&gt;
 *     &lt;enumeration value="lb"/&gt;
 *     &lt;enumeration value="mk"/&gt;
 *     &lt;enumeration value="mg"/&gt;
 *     &lt;enumeration value="ms"/&gt;
 *     &lt;enumeration value="ml"/&gt;
 *     &lt;enumeration value="mt"/&gt;
 *     &lt;enumeration value="gv"/&gt;
 *     &lt;enumeration value="mi"/&gt;
 *     &lt;enumeration value="mr"/&gt;
 *     &lt;enumeration value="mh"/&gt;
 *     &lt;enumeration value="mo"/&gt;
 *     &lt;enumeration value="mn"/&gt;
 *     &lt;enumeration value="na"/&gt;
 *     &lt;enumeration value="nv"/&gt;
 *     &lt;enumeration value="ng"/&gt;
 *     &lt;enumeration value="ne"/&gt;
 *     &lt;enumeration value="nd"/&gt;
 *     &lt;enumeration value="se"/&gt;
 *     &lt;enumeration value="no"/&gt;
 *     &lt;enumeration value="nb"/&gt;
 *     &lt;enumeration value="nn"/&gt;
 *     &lt;enumeration value="ny"/&gt;
 *     &lt;enumeration value="oc"/&gt;
 *     &lt;enumeration value="oj"/&gt;
 *     &lt;enumeration value="or"/&gt;
 *     &lt;enumeration value="om"/&gt;
 *     &lt;enumeration value="os"/&gt;
 *     &lt;enumeration value="pi"/&gt;
 *     &lt;enumeration value="pa"/&gt;
 *     &lt;enumeration value="fa"/&gt;
 *     &lt;enumeration value="pl"/&gt;
 *     &lt;enumeration value="pt"/&gt;
 *     &lt;enumeration value="ps"/&gt;
 *     &lt;enumeration value="qu"/&gt;
 *     &lt;enumeration value="rm"/&gt;
 *     &lt;enumeration value="ro"/&gt;
 *     &lt;enumeration value="rn"/&gt;
 *     &lt;enumeration value="ru"/&gt;
 *     &lt;enumeration value="sm"/&gt;
 *     &lt;enumeration value="sg"/&gt;
 *     &lt;enumeration value="sa"/&gt;
 *     &lt;enumeration value="sc"/&gt;
 *     &lt;enumeration value="gd"/&gt;
 *     &lt;enumeration value="sr"/&gt;
 *     &lt;enumeration value="sn"/&gt;
 *     &lt;enumeration value="ii"/&gt;
 *     &lt;enumeration value="sd"/&gt;
 *     &lt;enumeration value="si"/&gt;
 *     &lt;enumeration value="sk"/&gt;
 *     &lt;enumeration value="sl"/&gt;
 *     &lt;enumeration value="so"/&gt;
 *     &lt;enumeration value="nr"/&gt;
 *     &lt;enumeration value="st"/&gt;
 *     &lt;enumeration value="es"/&gt;
 *     &lt;enumeration value="su"/&gt;
 *     &lt;enumeration value="sw"/&gt;
 *     &lt;enumeration value="ss"/&gt;
 *     &lt;enumeration value="sv"/&gt;
 *     &lt;enumeration value="tl"/&gt;
 *     &lt;enumeration value="ty"/&gt;
 *     &lt;enumeration value="tg"/&gt;
 *     &lt;enumeration value="ta"/&gt;
 *     &lt;enumeration value="tt"/&gt;
 *     &lt;enumeration value="te"/&gt;
 *     &lt;enumeration value="th"/&gt;
 *     &lt;enumeration value="bo"/&gt;
 *     &lt;enumeration value="ti"/&gt;
 *     &lt;enumeration value="to"/&gt;
 *     &lt;enumeration value="ts"/&gt;
 *     &lt;enumeration value="tn"/&gt;
 *     &lt;enumeration value="tr"/&gt;
 *     &lt;enumeration value="tk"/&gt;
 *     &lt;enumeration value="tw"/&gt;
 *     &lt;enumeration value="ug"/&gt;
 *     &lt;enumeration value="uk"/&gt;
 *     &lt;enumeration value="ur"/&gt;
 *     &lt;enumeration value="uz"/&gt;
 *     &lt;enumeration value="ve"/&gt;
 *     &lt;enumeration value="vi"/&gt;
 *     &lt;enumeration value="vo"/&gt;
 *     &lt;enumeration value="wa"/&gt;
 *     &lt;enumeration value="cy"/&gt;
 *     &lt;enumeration value="wo"/&gt;
 *     &lt;enumeration value="xh"/&gt;
 *     &lt;enumeration value="ji"/&gt;
 *     &lt;enumeration value="yo"/&gt;
 *     &lt;enumeration value="za"/&gt;
 *     &lt;enumeration value="zu"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "language-code")
@XmlEnum
@Generated(value = "com.sun.tools.xjc.Driver", date = "2018-04-24T11:17:38-05:00", comments = "JAXB RI v2.2.11")
public enum LanguageCode {

    @XmlEnumValue("en")
    EN("en"),
    @XmlEnumValue("ab")
    AB("ab"),
    @XmlEnumValue("aa")
    AA("aa"),
    @XmlEnumValue("af")
    AF("af"),
    @XmlEnumValue("ak")
    AK("ak"),
    @XmlEnumValue("sq")
    SQ("sq"),
    @XmlEnumValue("am")
    AM("am"),
    @XmlEnumValue("ar")
    AR("ar"),
    @XmlEnumValue("an")
    AN("an"),
    @XmlEnumValue("hy")
    HY("hy"),
    @XmlEnumValue("as")
    AS("as"),
    @XmlEnumValue("av")
    AV("av"),
    @XmlEnumValue("ae")
    AE("ae"),
    @XmlEnumValue("ay")
    AY("ay"),
    @XmlEnumValue("az")
    AZ("az"),
    @XmlEnumValue("bm")
    BM("bm"),
    @XmlEnumValue("ba")
    BA("ba"),
    @XmlEnumValue("eu")
    EU("eu"),
    @XmlEnumValue("be")
    BE("be"),
    @XmlEnumValue("bn")
    BN("bn"),
    @XmlEnumValue("bh")
    BH("bh"),
    @XmlEnumValue("bi")
    BI("bi"),
    @XmlEnumValue("bs")
    BS("bs"),
    @XmlEnumValue("br")
    BR("br"),
    @XmlEnumValue("bg")
    BG("bg"),
    @XmlEnumValue("my")
    MY("my"),
    @XmlEnumValue("ca")
    CA("ca"),
    @XmlEnumValue("ch")
    CH("ch"),
    @XmlEnumValue("ce")
    CE("ce"),
    @XmlEnumValue("zh_CN")
    ZH_CN("zh_CN"),
    @XmlEnumValue("zh_TW")
    ZH_TW("zh_TW"),
    @XmlEnumValue("cu")
    CU("cu"),
    @XmlEnumValue("cv")
    CV("cv"),
    @XmlEnumValue("kw")
    KW("kw"),
    @XmlEnumValue("co")
    CO("co"),
    @XmlEnumValue("cr")
    CR("cr"),
    @XmlEnumValue("hr")
    HR("hr"),
    @XmlEnumValue("cs")
    CS("cs"),
    @XmlEnumValue("da")
    DA("da"),
    @XmlEnumValue("dv")
    DV("dv"),
    @XmlEnumValue("nl")
    NL("nl"),
    @XmlEnumValue("dz")
    DZ("dz"),
    @XmlEnumValue("eo")
    EO("eo"),
    @XmlEnumValue("et")
    ET("et"),
    @XmlEnumValue("ee")
    EE("ee"),
    @XmlEnumValue("fo")
    FO("fo"),
    @XmlEnumValue("fj")
    FJ("fj"),
    @XmlEnumValue("fi")
    FI("fi"),
    @XmlEnumValue("fr")
    FR("fr"),
    @XmlEnumValue("fy")
    FY("fy"),
    @XmlEnumValue("ff")
    FF("ff"),
    @XmlEnumValue("gl")
    GL("gl"),
    @XmlEnumValue("lg")
    LG("lg"),
    @XmlEnumValue("ka")
    KA("ka"),
    @XmlEnumValue("de")
    DE("de"),
    @XmlEnumValue("el")
    EL("el"),
    @XmlEnumValue("kl")
    KL("kl"),
    @XmlEnumValue("gn")
    GN("gn"),
    @XmlEnumValue("gu")
    GU("gu"),
    @XmlEnumValue("ht")
    HT("ht"),
    @XmlEnumValue("ha")
    HA("ha"),
    @XmlEnumValue("iw")
    IW("iw"),
    @XmlEnumValue("hz")
    HZ("hz"),
    @XmlEnumValue("hi")
    HI("hi"),
    @XmlEnumValue("ho")
    HO("ho"),
    @XmlEnumValue("hu")
    HU("hu"),
    @XmlEnumValue("is")
    IS("is"),
    @XmlEnumValue("io")
    IO("io"),
    @XmlEnumValue("ig")
    IG("ig"),
    @XmlEnumValue("in")
    IN("in"),
    @XmlEnumValue("ia")
    IA("ia"),
    @XmlEnumValue("ie")
    IE("ie"),
    @XmlEnumValue("iu")
    IU("iu"),
    @XmlEnumValue("ik")
    IK("ik"),
    @XmlEnumValue("ga")
    GA("ga"),
    @XmlEnumValue("it")
    IT("it"),
    @XmlEnumValue("ja")
    JA("ja"),
    @XmlEnumValue("jv")
    JV("jv"),
    @XmlEnumValue("kn")
    KN("kn"),
    @XmlEnumValue("kr")
    KR("kr"),
    @XmlEnumValue("ks")
    KS("ks"),
    @XmlEnumValue("kk")
    KK("kk"),
    @XmlEnumValue("km")
    KM("km"),
    @XmlEnumValue("ki")
    KI("ki"),
    @XmlEnumValue("rw")
    RW("rw"),
    @XmlEnumValue("ky")
    KY("ky"),
    @XmlEnumValue("kv")
    KV("kv"),
    @XmlEnumValue("kg")
    KG("kg"),
    @XmlEnumValue("ko")
    KO("ko"),
    @XmlEnumValue("ku")
    KU("ku"),
    @XmlEnumValue("kj")
    KJ("kj"),
    @XmlEnumValue("lo")
    LO("lo"),
    @XmlEnumValue("la")
    LA("la"),
    @XmlEnumValue("lv")
    LV("lv"),
    @XmlEnumValue("li")
    LI("li"),
    @XmlEnumValue("ln")
    LN("ln"),
    @XmlEnumValue("lt")
    LT("lt"),
    @XmlEnumValue("lu")
    LU("lu"),
    @XmlEnumValue("lb")
    LB("lb"),
    @XmlEnumValue("mk")
    MK("mk"),
    @XmlEnumValue("mg")
    MG("mg"),
    @XmlEnumValue("ms")
    MS("ms"),
    @XmlEnumValue("ml")
    ML("ml"),
    @XmlEnumValue("mt")
    MT("mt"),
    @XmlEnumValue("gv")
    GV("gv"),
    @XmlEnumValue("mi")
    MI("mi"),
    @XmlEnumValue("mr")
    MR("mr"),
    @XmlEnumValue("mh")
    MH("mh"),
    @XmlEnumValue("mo")
    MO("mo"),
    @XmlEnumValue("mn")
    MN("mn"),
    @XmlEnumValue("na")
    NA("na"),
    @XmlEnumValue("nv")
    NV("nv"),
    @XmlEnumValue("ng")
    NG("ng"),
    @XmlEnumValue("ne")
    NE("ne"),
    @XmlEnumValue("nd")
    ND("nd"),
    @XmlEnumValue("se")
    SE("se"),
    @XmlEnumValue("no")
    NO("no"),
    @XmlEnumValue("nb")
    NB("nb"),
    @XmlEnumValue("nn")
    NN("nn"),
    @XmlEnumValue("ny")
    NY("ny"),
    @XmlEnumValue("oc")
    OC("oc"),
    @XmlEnumValue("oj")
    OJ("oj"),
    @XmlEnumValue("or")
    OR("or"),
    @XmlEnumValue("om")
    OM("om"),
    @XmlEnumValue("os")
    OS("os"),
    @XmlEnumValue("pi")
    PI("pi"),
    @XmlEnumValue("pa")
    PA("pa"),
    @XmlEnumValue("fa")
    FA("fa"),
    @XmlEnumValue("pl")
    PL("pl"),
    @XmlEnumValue("pt")
    PT("pt"),
    @XmlEnumValue("ps")
    PS("ps"),
    @XmlEnumValue("qu")
    QU("qu"),
    @XmlEnumValue("rm")
    RM("rm"),
    @XmlEnumValue("ro")
    RO("ro"),
    @XmlEnumValue("rn")
    RN("rn"),
    @XmlEnumValue("ru")
    RU("ru"),
    @XmlEnumValue("sm")
    SM("sm"),
    @XmlEnumValue("sg")
    SG("sg"),
    @XmlEnumValue("sa")
    SA("sa"),
    @XmlEnumValue("sc")
    SC("sc"),
    @XmlEnumValue("gd")
    GD("gd"),
    @XmlEnumValue("sr")
    SR("sr"),
    @XmlEnumValue("sn")
    SN("sn"),
    @XmlEnumValue("ii")
    II("ii"),
    @XmlEnumValue("sd")
    SD("sd"),
    @XmlEnumValue("si")
    SI("si"),
    @XmlEnumValue("sk")
    SK("sk"),
    @XmlEnumValue("sl")
    SL("sl"),
    @XmlEnumValue("so")
    SO("so"),
    @XmlEnumValue("nr")
    NR("nr"),
    @XmlEnumValue("st")
    ST("st"),
    @XmlEnumValue("es")
    ES("es"),
    @XmlEnumValue("su")
    SU("su"),
    @XmlEnumValue("sw")
    SW("sw"),
    @XmlEnumValue("ss")
    SS("ss"),
    @XmlEnumValue("sv")
    SV("sv"),
    @XmlEnumValue("tl")
    TL("tl"),
    @XmlEnumValue("ty")
    TY("ty"),
    @XmlEnumValue("tg")
    TG("tg"),
    @XmlEnumValue("ta")
    TA("ta"),
    @XmlEnumValue("tt")
    TT("tt"),
    @XmlEnumValue("te")
    TE("te"),
    @XmlEnumValue("th")
    TH("th"),
    @XmlEnumValue("bo")
    BO("bo"),
    @XmlEnumValue("ti")
    TI("ti"),
    @XmlEnumValue("to")
    TO("to"),
    @XmlEnumValue("ts")
    TS("ts"),
    @XmlEnumValue("tn")
    TN("tn"),
    @XmlEnumValue("tr")
    TR("tr"),
    @XmlEnumValue("tk")
    TK("tk"),
    @XmlEnumValue("tw")
    TW("tw"),
    @XmlEnumValue("ug")
    UG("ug"),
    @XmlEnumValue("uk")
    UK("uk"),
    @XmlEnumValue("ur")
    UR("ur"),
    @XmlEnumValue("uz")
    UZ("uz"),
    @XmlEnumValue("ve")
    VE("ve"),
    @XmlEnumValue("vi")
    VI("vi"),
    @XmlEnumValue("vo")
    VO("vo"),
    @XmlEnumValue("wa")
    WA("wa"),
    @XmlEnumValue("cy")
    CY("cy"),
    @XmlEnumValue("wo")
    WO("wo"),
    @XmlEnumValue("xh")
    XH("xh"),
    @XmlEnumValue("ji")
    JI("ji"),
    @XmlEnumValue("yo")
    YO("yo"),
    @XmlEnumValue("za")
    ZA("za"),
    @XmlEnumValue("zu")
    ZU("zu");
    private final String value;

    LanguageCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LanguageCode fromValue(String v) {
        for (LanguageCode c: LanguageCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
