//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.24 at 11:17:38 AM CDT 
//


package org.orcid.jaxb.model.common_v2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.orcid.jaxb.model.common_v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Source_QNAME = new QName("http://www.orcid.org/ns/common", "source");
    private final static QName _ExternalIds_QNAME = new QName("http://www.orcid.org/ns/common", "external-ids");
    private final static QName _ExternalId_QNAME = new QName("http://www.orcid.org/ns/common", "external-id");
    private final static QName _LanguageCode_QNAME = new QName("http://www.orcid.org/ns/common", "language-code");
    private final static QName _ApplicationGroupOrcid_QNAME = new QName("http://www.orcid.org/ns/common", "application-group-orcid");
    private final static QName _ApplicationOrcid_QNAME = new QName("http://www.orcid.org/ns/common", "application-orcid");
    private final static QName _OrcidIdentifier_QNAME = new QName("http://www.orcid.org/ns/common", "orcid-identifier");
    private final static QName _ContributorOrcid_QNAME = new QName("http://www.orcid.org/ns/common", "contributor-orcid");
    private final static QName _GroupOrcidIdentifier_QNAME = new QName("http://www.orcid.org/ns/common", "group-orcid-identifier");
    private final static QName _SourceOrcid_QNAME = new QName("http://www.orcid.org/ns/common", "source-orcid");
    private final static QName _OrcidId_QNAME = new QName("http://www.orcid.org/ns/common", "orcid-id");
    private final static QName _FuzzyDate_QNAME = new QName("http://www.orcid.org/ns/common", "fuzzy-date");
    private final static QName _StartDate_QNAME = new QName("http://www.orcid.org/ns/common", "start-date");
    private final static QName _EndDate_QNAME = new QName("http://www.orcid.org/ns/common", "end-date");
    private final static QName _PublicationDate_QNAME = new QName("http://www.orcid.org/ns/common", "publication-date");
    private final static QName _Title_QNAME = new QName("http://www.orcid.org/ns/common", "title");
    private final static QName _Subtitle_QNAME = new QName("http://www.orcid.org/ns/common", "subtitle");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.orcid.jaxb.model.common_v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FuzzyDate }
     * 
     */
    public FuzzyDate createFuzzyDate() {
        return new FuzzyDate();
    }

    /**
     * Create an instance of {@link LastModifiedDate }
     * 
     */
    public LastModifiedDate createLastModifiedDate() {
        return new LastModifiedDate();
    }

    /**
     * Create an instance of {@link CreatedDate }
     * 
     */
    public CreatedDate createCreatedDate() {
        return new CreatedDate();
    }

    /**
     * Create an instance of {@link ReadDate }
     * 
     */
    public ReadDate createReadDate() {
        return new ReadDate();
    }

    /**
     * Create an instance of {@link ArchivedDate }
     * 
     */
    public ArchivedDate createArchivedDate() {
        return new ArchivedDate();
    }

    /**
     * Create an instance of {@link SentDate }
     * 
     */
    public SentDate createSentDate() {
        return new SentDate();
    }

    /**
     * Create an instance of {@link ApprovalDate }
     * 
     */
    public ApprovalDate createApprovalDate() {
        return new ApprovalDate();
    }

    /**
     * Create an instance of {@link SourceType }
     * 
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link ExternalIds }
     * 
     */
    public ExternalIds createExternalIds() {
        return new ExternalIds();
    }

    /**
     * Create an instance of {@link ExternalId }
     * 
     */
    public ExternalId createExternalId() {
        return new ExternalId();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link OrcidId }
     * 
     */
    public OrcidId createOrcidId() {
        return new OrcidId();
    }

    /**
     * Create an instance of {@link TranslatedTitle }
     * 
     */
    public TranslatedTitle createTranslatedTitle() {
        return new TranslatedTitle();
    }

    /**
     * Create an instance of {@link StringWithLangCode }
     * 
     */
    public StringWithLangCode createStringWithLangCode() {
        return new StringWithLangCode();
    }

    /**
     * Create an instance of {@link SourceName }
     * 
     */
    public SourceName createSourceName() {
        return new SourceName();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link OrganizationAddress }
     * 
     */
    public OrganizationAddress createOrganizationAddress() {
        return new OrganizationAddress();
    }

    /**
     * Create an instance of {@link DisambiguatedOrganization }
     * 
     */
    public DisambiguatedOrganization createDisambiguatedOrganization() {
        return new DisambiguatedOrganization();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link Url }
     * 
     */
    public Url createUrl() {
        return new Url();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ClientId }
     * 
     */
    public ClientId createClientId() {
        return new ClientId();
    }

    /**
     * Create an instance of {@link CreditName }
     * 
     */
    public CreditName createCreditName() {
        return new CreditName();
    }

    /**
     * Create an instance of {@link ContributorEmail }
     * 
     */
    public ContributorEmail createContributorEmail() {
        return new ContributorEmail();
    }

    /**
     * Create an instance of {@link ContributorAttributes }
     * 
     */
    public ContributorAttributes createContributorAttributes() {
        return new ContributorAttributes();
    }

    /**
     * Create an instance of {@link ElementSummary }
     * 
     */
    public ElementSummary createElementSummary() {
        return new ElementSummary();
    }

    /**
     * Create an instance of {@link FuzzyDate.Year }
     * 
     */
    public FuzzyDate.Year createFuzzyDateYear() {
        return new FuzzyDate.Year();
    }

    /**
     * Create an instance of {@link FuzzyDate.Month }
     * 
     */
    public FuzzyDate.Month createFuzzyDateMonth() {
        return new FuzzyDate.Month();
    }

    /**
     * Create an instance of {@link FuzzyDate.Day }
     * 
     */
    public FuzzyDate.Day createFuzzyDateDay() {
        return new FuzzyDate.Day();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "source")
    public JAXBElement<SourceType> createSource(SourceType value) {
        return new JAXBElement<SourceType>(_Source_QNAME, SourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalIds }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "external-ids")
    public JAXBElement<ExternalIds> createExternalIds(ExternalIds value) {
        return new JAXBElement<ExternalIds>(_ExternalIds_QNAME, ExternalIds.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "external-id")
    public JAXBElement<ExternalId> createExternalId(ExternalId value) {
        return new JAXBElement<ExternalId>(_ExternalId_QNAME, ExternalId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "language-code")
    public JAXBElement<LanguageCode> createLanguageCode(LanguageCode value) {
        return new JAXBElement<LanguageCode>(_LanguageCode_QNAME, LanguageCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "application-group-orcid")
    public JAXBElement<OrcidId> createApplicationGroupOrcid(OrcidId value) {
        return new JAXBElement<OrcidId>(_ApplicationGroupOrcid_QNAME, OrcidId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "application-orcid")
    public JAXBElement<OrcidId> createApplicationOrcid(OrcidId value) {
        return new JAXBElement<OrcidId>(_ApplicationOrcid_QNAME, OrcidId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "orcid-identifier")
    public JAXBElement<OrcidId> createOrcidIdentifier(OrcidId value) {
        return new JAXBElement<OrcidId>(_OrcidIdentifier_QNAME, OrcidId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "contributor-orcid")
    public JAXBElement<OrcidId> createContributorOrcid(OrcidId value) {
        return new JAXBElement<OrcidId>(_ContributorOrcid_QNAME, OrcidId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "group-orcid-identifier")
    public JAXBElement<OrcidId> createGroupOrcidIdentifier(OrcidId value) {
        return new JAXBElement<OrcidId>(_GroupOrcidIdentifier_QNAME, OrcidId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "source-orcid")
    public JAXBElement<OrcidId> createSourceOrcid(OrcidId value) {
        return new JAXBElement<OrcidId>(_SourceOrcid_QNAME, OrcidId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "orcid-id")
    public JAXBElement<OrcidId> createOrcidId(OrcidId value) {
        return new JAXBElement<OrcidId>(_OrcidId_QNAME, OrcidId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuzzyDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "fuzzy-date")
    public JAXBElement<FuzzyDate> createFuzzyDate(FuzzyDate value) {
        return new JAXBElement<FuzzyDate>(_FuzzyDate_QNAME, FuzzyDate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuzzyDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "start-date")
    public JAXBElement<FuzzyDate> createStartDate(FuzzyDate value) {
        return new JAXBElement<FuzzyDate>(_StartDate_QNAME, FuzzyDate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuzzyDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "end-date")
    public JAXBElement<FuzzyDate> createEndDate(FuzzyDate value) {
        return new JAXBElement<FuzzyDate>(_EndDate_QNAME, FuzzyDate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuzzyDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "publication-date")
    public JAXBElement<FuzzyDate> createPublicationDate(FuzzyDate value) {
        return new JAXBElement<FuzzyDate>(_PublicationDate_QNAME, FuzzyDate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "subtitle")
    public JAXBElement<String> createSubtitle(String value) {
        return new JAXBElement<String>(_Subtitle_QNAME, String.class, null, value);
    }

}
