//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.24 at 11:17:38 AM CDT 
//


package org.orcid.jaxb.model.record_v2;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contributor-role.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="contributor-role"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="lead"/&gt;
 *     &lt;enumeration value="co-lead"/&gt;
 *     &lt;enumeration value="supported-by"/&gt;
 *     &lt;enumeration value="other-contribution"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "contributor-role", namespace = "http://www.orcid.org/ns/funding")
@XmlEnum
@Generated(value = "com.sun.tools.xjc.Driver", date = "2018-04-24T11:17:38-05:00", comments = "JAXB RI v2.2.11")
public enum FundingContributorRole {

    @XmlEnumValue("lead")
    LEAD("lead"),
    @XmlEnumValue("co-lead")
    CO_LEAD("co-lead"),
    @XmlEnumValue("supported-by")
    SUPPORTED_BY("supported-by"),
    @XmlEnumValue("other-contribution")
    OTHER_CONTRIBUTION("other-contribution");
    private final String value;

    FundingContributorRole(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FundingContributorRole fromValue(String v) {
        for (FundingContributorRole c: FundingContributorRole.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
