//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.24 at 11:17:38 AM CDT 
//


package org.orcid.jaxb.model.record_v2;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for role.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="role"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="reviewer"/&gt;
 *     &lt;enumeration value="editor"/&gt;
 *     &lt;enumeration value="member"/&gt;
 *     &lt;enumeration value="chair"/&gt;
 *     &lt;enumeration value="organizer"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "role", namespace = "http://www.orcid.org/ns/peer-review")
@XmlEnum
@Generated(value = "com.sun.tools.xjc.Driver", date = "2018-04-24T11:17:38-05:00", comments = "JAXB RI v2.2.11")
public enum Role {


    /**
     * 
     * 						A person who formally assess or examines an
     * 						output with a view to
     * 						commenting and evaluating it.
     * 					
     * 
     */
    @XmlEnumValue("reviewer")
    REVIEWER("reviewer"),

    /**
     * A person who coordinates reviews and/or is
     * 						responsible for decision making on the content of a publication.
     * 					
     * 
     */
    @XmlEnumValue("editor")
    EDITOR("editor"),

    /**
     * A person participating in a process, committee or
     * 						activity.
     * 					
     * 
     */
    @XmlEnumValue("member")
    MEMBER("member"),

    /**
     * A person who coordinates reviews and/or is
     * 						responsible for decision making on the content of a conference.
     * 					
     * 
     */
    @XmlEnumValue("chair")
    CHAIR("chair"),

    /**
     * A person who makes arrangements or preparations
     * 						for an event or activity.
     * 					
     * 
     */
    @XmlEnumValue("organizer")
    ORGANIZER("organizer");
    private final String value;

    Role(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Role fromValue(String v) {
        for (Role c: Role.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
