//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 07:22:19 PM CEST 
//


package org.orcid.jaxb.model.common_v3;

import java.io.Serializable;
import java.math.BigInteger;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for affiliation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="affiliation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.orcid.org/ns/common}element-summary"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="department-name" type="{http://www.orcid.org/ns/common}long-text" minOccurs="0"/&gt;
 *         &lt;element name="role-title" type="{http://www.orcid.org/ns/common}long-text" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/common}start-date" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/common}end-date" minOccurs="0"/&gt;
 *         &lt;element name="organization" type="{http://www.orcid.org/ns/common}organization"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/common}url" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/common}external-ids" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "affiliation", propOrder = {
    "departmentName",
    "roleTitle",
    "startDate",
    "endDate",
    "organization",
    "url",
    "externalIds"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
public class Affiliation
    extends ElementSummary
    implements Serializable, ToString
{

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    private final static long serialVersionUID = 1L;
    @XmlElement(name = "department-name")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected String departmentName;
    @XmlElement(name = "role-title")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected String roleTitle;
    @XmlElement(name = "start-date")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected FuzzyDate startDate;
    @XmlElement(name = "end-date")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected FuzzyDate endDate;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected Organization organization;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected Url url;
    @XmlElement(name = "external-ids")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    protected ExternalIds externalIds;

    /**
     * Default no-arg constructor
     * 
     */
    public Affiliation() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public Affiliation(final CreatedDate createdDate, final LastModifiedDate lastModifiedDate, final SourceType source, final BigInteger putCode, final Visibility visibility, final String displayIndex, final String path, final String departmentName, final String roleTitle, final FuzzyDate startDate, final FuzzyDate endDate, final Organization organization, final Url url, final ExternalIds externalIds) {
        super(createdDate, lastModifiedDate, source, putCode, visibility, displayIndex, path);
        this.departmentName = departmentName;
        this.roleTitle = roleTitle;
        this.startDate = startDate;
        this.endDate = endDate;
        this.organization = organization;
        this.url = url;
        this.externalIds = externalIds;
    }

    /**
     * Gets the value of the departmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * Sets the value of the departmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setDepartmentName(String value) {
        this.departmentName = value;
    }

    /**
     * Gets the value of the roleTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public String getRoleTitle() {
        return roleTitle;
    }

    /**
     * Sets the value of the roleTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setRoleTitle(String value) {
        this.roleTitle = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link FuzzyDate }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public FuzzyDate getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuzzyDate }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setStartDate(FuzzyDate value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link FuzzyDate }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public FuzzyDate getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuzzyDate }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setEndDate(FuzzyDate value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public Organization getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setOrganization(Organization value) {
        this.organization = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link Url }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public Url getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link Url }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setUrl(Url value) {
        this.url = value;
    }

    /**
     * Gets the value of the externalIds property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalIds }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public ExternalIds getExternalIds() {
        return externalIds;
    }

    /**
     * Sets the value of the externalIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalIds }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public void setExternalIds(ExternalIds value) {
        this.externalIds = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-03T07:22:19+02:00", comments = "JAXB RI v2.2.11")
    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            String theDepartmentName;
            theDepartmentName = this.getDepartmentName();
            strategy.appendField(locator, this, "departmentName", buffer, theDepartmentName);
        }
        {
            String theRoleTitle;
            theRoleTitle = this.getRoleTitle();
            strategy.appendField(locator, this, "roleTitle", buffer, theRoleTitle);
        }
        {
            FuzzyDate theStartDate;
            theStartDate = this.getStartDate();
            strategy.appendField(locator, this, "startDate", buffer, theStartDate);
        }
        {
            FuzzyDate theEndDate;
            theEndDate = this.getEndDate();
            strategy.appendField(locator, this, "endDate", buffer, theEndDate);
        }
        {
            Organization theOrganization;
            theOrganization = this.getOrganization();
            strategy.appendField(locator, this, "organization", buffer, theOrganization);
        }
        {
            Url theUrl;
            theUrl = this.getUrl();
            strategy.appendField(locator, this, "url", buffer, theUrl);
        }
        {
            ExternalIds theExternalIds;
            theExternalIds = this.getExternalIds();
            strategy.appendField(locator, this, "externalIds", buffer, theExternalIds);
        }
        return buffer;
    }

}
