//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 06:01:23 PM CEST 
//


package org.orcid.jaxb.model.common_v3;

import java.io.Serializable;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.orcid.jaxb.model.record_v3.CreditNameType;


/**
 * The name to use for the researcher or contributor
 * 				when credited or cited, for example, in an article or index, or as a
 * 				funding contributor. The value of this field also is used as the
 * 				display name for the researcher or contributor in the ORCID Registry
 * 				in their ORCID Record, or when listed as a contributor on other
 * 				ORCID Records. If this element is NULL, given-name family-name will
 * 				be used for display purposes, with a visibility of "public". The
 * 				visibility attribute (private, limited or public) can be set at
 * 				record creation, and indicates who can see this section of
 * 				information.
 * 			
 * 
 * <p>Java class for credit-name complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="credit-name"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.orcid.org/ns/common&gt;string-150"&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "credit-name", propOrder = {
    "value"
})
@XmlSeeAlso({
    CreditNameType.class
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-16T06:01:23+02:00", comments = "JAXB RI v2.2.11")
public class CreditName implements Serializable, ToString
{

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-16T06:01:23+02:00", comments = "JAXB RI v2.2.11")
    private final static long serialVersionUID = 1L;
    @XmlValue
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-16T06:01:23+02:00", comments = "JAXB RI v2.2.11")
    protected String value;

    /**
     * Default no-arg constructor
     * 
     */
    public CreditName() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public CreditName(final String value) {
        this.value = value;
    }

    /**
     * A non-empty string that has a maximum size of 150
     * 				characters
     * 			
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-16T06:01:23+02:00", comments = "JAXB RI v2.2.11")
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-16T06:01:23+02:00", comments = "JAXB RI v2.2.11")
    public void setValue(String value) {
        this.value = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-16T06:01:23+02:00", comments = "JAXB RI v2.2.11")
    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-16T06:01:23+02:00", comments = "JAXB RI v2.2.11")
    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-16T06:01:23+02:00", comments = "JAXB RI v2.2.11")
    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theValue;
            theValue = this.getValue();
            strategy.appendField(locator, this, "value", buffer, theValue);
        }
        return buffer;
    }

}
