//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 09:44:26 AM CEST 
//


package org.orcid.jaxb.model.common_v3;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for visibility.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="visibility"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="private"/&gt;
 *     &lt;enumeration value="limited"/&gt;
 *     &lt;enumeration value="public"/&gt;
 *     &lt;enumeration value="registered-only"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "visibility")
@XmlEnum
@Generated(value = "com.sun.tools.xjc.Driver", date = "2020-04-17T09:44:26+02:00", comments = "JAXB RI v2.2.11")
public enum Visibility {


    /**
     * The data can only be seen by the researcher or
     * 						contributor. This data may be used internally by ORCID for Record
     * 						disambiguation purposes.
     * 					
     * 
     */
    @XmlEnumValue("private")
    PRIVATE("private"),

    /**
     * The data can only be seen by trusted parties
     * 						(organizations or people) as indicated by the researcher or
     * 						contributor. This information is only shared with systems that the
     * 						researcher or contributor has specifically granted authorization
     * 						(using OAuth).
     * 					
     * 
     */
    @XmlEnumValue("limited")
    LIMITED("limited"),

    /**
     * The data can be seen by anyone. It is publically
     * 						available via the ORCID Registry website and the public API
     * 						without further authroization by the researcher or contributor.
     * 					
     * 
     */
    @XmlEnumValue("public")
    PUBLIC("public"),

    /**
     * The data is shared only with the registered user.
     * 					
     * 
     */
    @XmlEnumValue("registered-only")
    REGISTERED_ONLY("registered-only");
    private final String value;

    Visibility(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Visibility fromValue(String v) {
        for (Visibility c: Visibility.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
